### PR TITLE
Nicer Readme

### LINKED ISSUE #638: [TODO] Add contributors to the readme to give them credit
Add contributors to the readme to give them the credit they deserve & thank them.

### PR DESCRIPTION
**Pull request by inson1**
Fixes: #638

### CODE REVIEW

**Comment by azgaresncf** [comment]
just change I Still Dont Care About Cookies to I still don't care about cookies
get rid of 
```
## Fork of the popular "I don't care about cookies" extensiont

Get rid of cookie warnings from almost all websites!
```
otherwise it is perfect

**Comment by azgaresncf** [comment]
and there is the edge extension to add
https://microsoftedge.microsoft.com/addons/detail/i-still-dont-care-about-/kkacdgacpkediooahopgcbdahlpipheh

**Comment by inson1** [comment]
edge link is already there
name was changed
I would let it be there - @OhMyGuus What do you think?

**Comment by inson1** [comment]
@OhMyGuus api url doesnt work

**Comment by inson1** [comment]
I allso created https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies-Api/pull/2

**Comment by OhMyGuus** [comment]
Looks good !

**Comment by inson1** [comment]
@OhMyGuus then merge it please :)

**Pull request merged**
