### PR TITLE
Fix tweakers.net

### LINKED ISSUE #5637: [REQ] tweakers.net
Someone reported anonymously: 
  ### Website URL

https://tweakers.net

### What browser are u using?

Firefox 114

### Version

1.1.1

### PR DESCRIPTION
**Pull request by claudiodekker**
Fixes #5637

### CODE REVIEW

**Comment by OhMyGuus** [comment]
Disabling all, cookies on tweakers will break a lot of articles. This is the reason that "Ingesloten content van derden
" is clicked & enabled on tweakers. 
image

**Comment by claudiodekker** [comment]
Ah, I wasn't aware of this. I'll re-adjust it in a bit!

**Comment by claudiodekker** [comment]
Alright, I've reverted the changes, and have wrapped the "ingesloten content van derden" switch in an optional call.

I believe that the reason for this (which took me a while to understand) is that by default, Tweakers already sets those flags enabled, and because the script isn't able to find any disabled flags, it just hangs/stops there.

(The way I've verified this, is by adding an additional flag (`.koekie_bar .relevantAds .notSelect.toggleSwitch`) to purposefully enable the "Relevantere advertenties" flag, and by moving this up and down the stack until it started breaking.)

**Comment by OhMyGuus** [comment]
Thanks 👍

**Pull request merged**
