### PR TITLE
fixing multiple websites

### LINKED ISSUE #2547: [REQ] www.uni-passau.de
Someone reported anonymously: 
  ### Website URL

https://www.uni-passau.de

### What browser are u using?

Firefox 110

### Version

1.1.1

### LINKED ISSUE #2549: [REQ] www.sunroom.it
Someone reported anonymously: 
  ### Website URL

https://www.sunroom.it

### What browser are u using?

Firefox 110

### Version

1.1.1

### Notes

Cookies requested

### LINKED ISSUE #2550: [REQ] www.tulipsmarket.com
Someone reported anonymously: 
  ### Website URL

https://www.tulipsmarket.com

### What browser are u using?

Firefox 110

### Version

1.1.1

### Notes

Images not showing, search not working

### LINKED ISSUE #2554: [REQ] www.object-carpet.com
Someone reported anonymously: 
  ### Website URL

https://www.object-carpet.com

### What browser are u using?

Chrome 110

### Version

1.1.1

### Notes

Seite hat Grauschleier

### LINKED ISSUE #2555: [REQ] tricount.com
Someone reported anonymously: 
  ### Website URL

https://tricount.com

### What browser are u using?

Firefox 110

### Version

1.1.1

### Notes

la web-app ne s'active pas (tricount webapp doesn't launch)

### LINKED ISSUE #2557: [REQ] www.jobware.de
Someone reported anonymously: 
  ### Website URL

https://www.jobware.de

### What browser are u using?

Firefox 110

### Version

1.1.1

### LINKED ISSUE #2560: [REQ] www.baden-tv.com
Someone reported anonymously: 
  ### Website URL

https://www.baden-tv.com

### What browser are u using?

Firefox 110

### Version

1.1.1

### LINKED ISSUE #2562: [REQ] app.outwrite.com
Someone reported anonymously: 
  ### Website URL

https://app.outwrite.com

### What browser are u using?

Edge 110

### Version

1.0.10

### PR DESCRIPTION
**Pull request by ghost**
# context
As the development of this extension is paused, by maintaining this repository, I want to contribute to it to help the developer out, even if it is going to be a tough work.

# goal
- Block as many CSS selectors as possible (temporary selectors will be changed later)
- Otherwise, block Javascript scripts or urls
- Otherwise, make rules with click handler (e.g : GMX) or the other handlers (e.g: Instagram, by trying to click on the popup's buttons [and then delete the cookies ???])...

### CODE REVIEW

**Comment by dreirund** [comment]
@azgaresncf: Since it seems that the maintainer of this, @OhMyGuus, is not active on this project anymore: Do you want to make your fork kind of "official", e.g. provide release builds and bring it to [addons.mozilla.org](http://addons.mozilla.org/), or at least allow for automatic update from your repository?

Regards!

**Comment by azgaresncf** [comment]
> @azgaresncf: Since it seems that the maintainer of this, @OhMyGuus, is not active on this project anymore: Do you want to make your fork kind of "official", e.g. provide release builds and bring it to [addons.mozilla.org](http://addons.mozilla.org/), or at least allow for automatic update from your repository?
> 
> Regards!

I will think about it ASAP.

**Comment by azgaresncf** [comment]
> > @azgaresncf: Since it seems that the maintainer of this, @OhMyGuus, is not active on this project anymore: Do you want to make your fork kind of "official", e.g. provide release builds and bring it to [addons.mozilla.org](http://addons.mozilla.org/), or at least allow for automatic update from your repository?
> > Regards!
> 
> I will think about it ASAP.

So, I think that an (_another_) fork of this repo should be a good idea, but I'm getting two problems:
1) I'm not an expert at ALL at CSS selector, button clicking and so on... So any kind of help for **only SOME rules** may be a good option for me (even though I can block a lot of useless CSS selectors).
2) I'm seriously questioning myself about the usefulness of this plugin, as extensions such as uBlock Origin are blocking **more and more** cookies pop-ups (even with the hardcore ones, such as Instagram or Google). So a lot of people should use the plugin in order to be really useful.

But the advantage is that it can make a good challenge for me, because unfortunately, the developer have made some mistakes that are (hypothetically) the reasons of why he does no longer maintain the plugin (the "Anonymous Request"...).

For the moment, I'm keeping the fork, and if you've got any ideas, please tell me.

**Comment by dreirund** [comment]
> > > @azgaresncf: Since it seems that the maintainer of this,
> > > @OhMyGuus, is not active on this project anymore: Do you want to
> > > make your fork kind of "official", e.g. provide release builds
> > > and bring it to [addons.mozilla.org](http://addons.mozilla.org/),
> > > or at least allow for automatic update from your repository?
> > > Regards!  
> > 
> > I will think about it ASAP.  
> 
> So, I think that an (_another_) fork of this repo should be a good
> idea, but I'm getting two problems: 1) I'm not an expert at ALL at
> CSS selector, button clicking and so on... So any kind of help for
> **only SOME rules** may be a good option for me (even though I can
> block a lot of useless CSS selectors). 2) I'm seriously questioning
> myself about the usefulness of this plugin, as extensions such as
> uBlock Origin are blocking **more and more** cookies pop-ups (even
> with the hardcore ones, such as Instagram or Google). So a lot of
> people should use the plugin in order to be really useful.
> 
> But the advantage is that it can make a good challenge for me,
> because unfortunately, the developer have made some mistakes that are
> (hypothetically) the reasons of why he does no longer maintain the
> plugin (the "Anonymous Request"...).
> 
> For the moment, I'm keeping the fork, and if you've got any ideas,
> please tell me.

I also have no more ideas, I even know less than you about web
technology.

The only idea I also have it to make the reporting/ request
functionality different. Maybe not even as github issues, but a system
that

* automatically detects duplicates,
* allows to distinguish host and detailed URL (sometimes only some
  sites on a server don't work).

Regarding the uBlock Origin case: I have uBlock Origin, but if I
disable "I don't care about cookies" I get a lot of cookie banners.

Regards!

**Comment by OhMyGuus** [comment]
Moved the discussion about my inactivity to: #10278 
You are fine to talk about forks or anything on that issue as well (which is pinned, I will also put an link to the issue in the readme).
Thanks a lot for the fixes for those sites, and again sorry.

**Pull request merged**
