### PR TITLE
Support for ludigoodies.com

### LINKED ISSUE #76: [REQ] Website request: https://ludigoodies.com/
**Website URL(s)**

https://ludigoodies.com/

- Example.com

**Browser**
[x] Firefox
[] Chrome

**Extension version**
V1.0.3

### PR DESCRIPTION
**Pull request by appeasementPolitik**
Closes #76 

Please do give feedback

### CODE REVIEW

**Comment by OhMyGuus** [comment]
Thanks for the help, contributions 👍 😄
I would of used the localstorage here, since this banner & the CSS selector are quite generic and could be used for different things like a warning for a recall.

**Comment by OhMyGuus** [comment]
Oh what a timing xD

**Comment by appeasementPolitik** [comment]
Lol, hold on still comitting the rules.json

**Comment by appeasementPolitik** [comment]
Oh nevermind you also commited haha

**Comment by OhMyGuus** [comment]
> Oh nevermind you also commited haha

yeah I moved it towards to just blocking the JS file, since its a plugin that is most likely used on other websites as well. 
Thanks anyway for the contribution and the help 👍 (and sorry for finishing your PR want to release 1.0.4 today with all the fixes for websites)

**Comment by appeasementPolitik** [comment]
Haha good to hear, no worries

**Pull request merged**
