### PR TITLE
Name, Version, Author update

### PR DESCRIPTION
**Pull request by OhMyGuus**
### Changes to the Name, Version, Author

- [x] #18 - "OhMyGuus and Community (ex-Daniel Kladnik)" 
- [x]  #23   (Going to decide today)
- [ ] Updated the Version (To 1.0.1 ) for a fresh start

### CODE REVIEW

**Comment by Alcaro** [comment]
I'd change 'ex-' to 'originally'. Using ex- implies that Daniel Kladnik is no longer Daniel Kladnik.

**Comment by Erghel** [comment]
> I'd change 'ex-' to 'originally'. Using ex- implies that Daniel Kladnik is no longer Daniel Kladnik.

Good point. 
I agree with you.

**Comment by winskil** [comment]
I was wondering should the example domain be changed from `domain.com` to `example.com` as domain.com is a domain registrar?

Screenshot 2022-09-25 at 03 14 48

**Review by winskil — COMMENTED** [review]
Change the example domain from "domain.com" to "example.com"

**Comment by OhMyGuus** [comment]
> Change the example domain from "domain.com" to "example.com"

Will do this in another PR, this PR is only scoped for the name, version, Author.

**Pull request merged**
