### PR TITLE
Fix for reported websites #15

### LINKED ISSUE #832: [REQ] www.marubun.co.jp
Someone reported anonymously: 
  ### Website URL

https://www.marubun.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #833: [REQ] maruchiba.jp
Someone reported anonymously: 
  ### Website URL

https://maruchiba.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #834: [REQ] marketing.nikkei.com
Someone reported anonymously: 
  ### Website URL

https://marketing.nikkei.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #835: [REQ] www.microjet.com.tw
Someone reported anonymously: 
  ### Website URL

https://www.microjet.com.tw

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #836: [REQ] mitsubishicarbide.net
Someone reported anonymously: 
  ### Website URL

https://mitsubishicarbide.net

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #837: [REQ] www.nlc-japan.com
Someone reported anonymously: 
  ### Website URL

https://www.nlc-japan.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #838: [REQ] valorholdings.co.jp
Someone reported anonymously: 
  ### Website URL

https://valorholdings.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #840: [REQ] moresco.co.jp
Someone reported anonymously: 
  ### Website URL

https://moresco.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #841: [REQ] www.mt-pharma.co.jp
Someone reported anonymously: 
  ### Website URL

https://www.mt-pharma.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #842: [REQ] music-avenue.yamahamusic.jp
Someone reported anonymously: 
  ### Website URL

https://music-avenue.yamahamusic.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #843: [REQ] myair2.resmed.com
Someone reported anonymously: 
  ### Website URL

https://myair2.resmed.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #844: [REQ] www.navita.co.jp
Someone reported anonymously: 
  ### Website URL

https://www.navita.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #845: [REQ] www.ncsoft.jp
Someone reported anonymously: 
  ### Website URL

https://www.ncsoft.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #846: [REQ] www.neimanmarcus.com
Someone reported anonymously: 
  ### Website URL

https://www.neimanmarcus.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #847: [REQ] www.nyit.edu
Someone reported anonymously: 
  ### Website URL

https://www.nyit.edu

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #848: [REQ] opentip.kaspersky.com
Someone reported anonymously: 
  ### Website URL

https://opentip.kaspersky.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #849: [REQ] www.pacsun.com
Someone reported anonymously: 
  ### Website URL

https://www.pacsun.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #850: [REQ] www.pdftoexcel.com
Someone reported anonymously: 
  ### Website URL

https://www.pdftoexcel.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #851: [REQ] pictures.reuters.com
Someone reported anonymously: 
  ### Website URL

https://pictures.reuters.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #852: [REQ] pie.co.jp
Someone reported anonymously: 
  ### Website URL

https://pie.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #854: [REQ] www.pixilart.com
Someone reported anonymously: 
  ### Website URL

https://www.pixilart.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #855: [REQ] plusjam.jp
Someone reported anonymously: 
  ### Website URL

https://plusjam.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #857: [REQ] jp.pronews.com
Someone reported anonymously: 
  ### Website URL

https://jp.pronews.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #859: [REQ] www.royalpanda.com
Someone reported anonymously: 
  ### Website URL

https://www.royalpanda.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #860: [REQ] www.sankeibldg.co.jp
Someone reported anonymously: 
  ### Website URL

https://www.sankeibldg.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #861: [REQ] www.scania.com
Someone reported anonymously: 
  ### Website URL

https://www.scania.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #862: [REQ] toyosenpaku.com
Someone reported anonymously: 
  ### Website URL

https://toyosenpaku.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #863: [REQ] www.seminolestate.edu
Someone reported anonymously: 
  ### Website URL

https://www.seminolestate.edu

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #864: [REQ] seagaia.co.jp
Someone reported anonymously: 
  ### Website URL

https://seagaia.co.jp

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #865: [REQ] www.shichida.com
Someone reported anonymously: 
  ### Website URL

https://www.shichida.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #866: [REQ] www.kuki.cz
Someone reported anonymously: 
  ### Website URL

https://www.kuki.cz

### What browser are u using?

Firefox 107

### Version

1.0.10

### Notes

no scroll

### LINKED ISSUE #867: [REQ] simcast.com
Someone reported anonymously: 
  ### Website URL

https://simcast.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #868: [REQ] www.labro.com.pl
Someone reported anonymously: 
  ### Website URL

https://www.labro.com.pl

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #869: [REQ] www.smcworld.com
Someone reported anonymously: 
  ### Website URL

https://www.smcworld.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #870: [REQ] passbase.com
Someone reported anonymously: 
  ### Website URL

https://passbase.com

### What browser are u using?

Firefox 107

### Version

1.0.10

### LINKED ISSUE #871: [REQ] www.dreamworks.com
Someone reported anonymously: 
  ### Website URL

https://www.dreamworks.com

### What browser are u using?

Firefox 108

### Version

1.1.0

### LINKED ISSUE #873: [REQ] geotastic.net
Someone reported anonymously: 
  ### Website URL

https://geotastic.net

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #875: [REQ] www.beefeater.co.uk
Someone reported anonymously: 
  ### Website URL

https://www.beefeater.co.uk

### What browser are u using?

Chrome 108

### Version

1.1.0

### LINKED ISSUE #877: [REQ] chem-space.com
Someone reported anonymously: 
  ### Website URL

https://chem-space.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #878: [REQ] www.oponeo.nl
Someone reported anonymously: 
  ### Website URL

https://www.oponeo.nl

### What browser are u using?

Firefox 107

### Version

1.1.0

### Notes

Cookie warning

### LINKED ISSUE #880: [REQ] www.warnerbros.com
Someone reported anonymously: 
  ### Website URL

https://www.warnerbros.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #881: [REQ] bootstrap.academy
Someone reported anonymously: 
  ### Website URL

https://bootstrap.academy

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #882: [REQ] www.buyzoxs.de
Someone reported anonymously: 
  ### Website URL

https://www.buyzoxs.de

### What browser are u using?

Firefox 106

### Version

1.1.0

### LINKED ISSUE #883: [REQ] foxracing.ro
Someone reported anonymously: 
  ### Website URL

https://foxracing.ro

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #884: [REQ] intellias.com
Someone reported anonymously: 
  ### Website URL

https://intellias.com

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #887: [REQ] www.promobit.com.br
Someone reported anonymously: 
  ### Website URL

https://www.promobit.com.br

### What browser are u using?

Edge 107

### Version

1.0.9

### Notes

https://www.promobit.com.br/

### LINKED ISSUE #889: [REQ] fvd.nl
Someone reported anonymously: 
  ### Website URL

https://fvd.nl

### What browser are u using?

Firefox 106

### Version

1.1.0

### Notes

cookie warning at the bottom with the class div.fixed

### LINKED ISSUE #890: [REQ] roshtein.com
Someone reported anonymously: 
  ### Website URL

https://roshtein.com

### What browser are u using?

Chrome 107

### Version

1.1.0

### Notes

Screen is blurry unless i disable this and accept cookies.

### LINKED ISSUE #892: [REQ] www.magazineluiza.com.br
Someone reported anonymously: 
  ### Website URL

https://www.magazineluiza.com.br

### What browser are u using?

Firefox 107

### Version

1.1.0

### Notes

https://www.magazineluiza.com.br/

### LINKED ISSUE #894: [REQ] www.kteohellas.gr
Someone reported anonymously: 
  ### Website URL

https://www.kteohellas.gr

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #895: [REQ] shiftdelete.net
Someone reported anonymously: 
  ### Website URL

https://shiftdelete.net

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #896: [REQ] afaudio.co.uk
Someone reported anonymously: 
  ### Website URL

https://afaudio.co.uk

### What browser are u using?

Firefox 107

### Version

1.1.0

### LINKED ISSUE #899: [REQ] www.kokoomus.fi
Someone reported anonymously: 
  ### Website URL

https://www.kokoomus.fi

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #901: [REQ] allegro.cz
Someone reported anonymously: 
  ### Website URL

https://allegro.cz

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #902: [REQ] pah.org.pl
Someone reported anonymously: 
  ### Website URL

https://pah.org.pl

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #903: [REQ] www.cupt.gov.pl
Someone reported anonymously: 
  ### Website URL

https://www.cupt.gov.pl

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #904: [REQ] biznes.plus.pl
Someone reported anonymously: 
  ### Website URL

https://biznes.plus.pl

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #905: [REQ] www.workbreakdownstructure.com
Someone reported anonymously: 
  ### Website URL

https://www.workbreakdownstructure.com

### What browser are u using?

Chrome 107

### Version

1.1.0

### Notes

bottom bar cookie popup, doesn't allow to not agree either

### LINKED ISSUE #907: [REQ] fanipogody.pl
Someone reported anonymously: 
  ### Website URL

https://fanipogody.pl

### What browser are u using?

Chrome 107

### Version

1.1.0

### Notes

Scrolling not working

### LINKED ISSUE #908: [REQ] worksmile.com
Someone reported anonymously: 
  ### Website URL

https://worksmile.com

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #909: [REQ] dryg.pl
Someone reported anonymously: 
  ### Website URL

https://dryg.pl

### What browser are u using?

Chrome 107

### Version

1.1.0

### LINKED ISSUE #910: [REQ] theprotocol.it
Someone reported anonymously: 
  ### Website URL

https://theprotocol.it

### What browser are u using?

Chrome 107

### Version

1.1.0

### PR DESCRIPTION
**Pull request by appeasementPolitik**
I'll also use this format
- fixes #832
- fixes #833
- fixes #834
- fixes #835
- fixes #836
- fixes #837
- fixes #838
- fixes #840
- fixes #841
- fixes #842
- fixes #843
- fixes #844
- fixes #845
- fixes #846
- fixes #847
- fixes #848
- fixes #849
- fixes #850
- fixes #851
- fixes #852
- fixes #854
- fixes #855 
- fixes #857 
- fixes #859 
- fixes #860 
- fixes #861 
- fixes #862 
- fixes #863 
- fixes #864 
- fixes #865 
- fixes #866 
- fixes #867 
- fixes #868 
- fixes #869 
- fixes #870
- fixes #871
- fixes #873
- fixes #875
- fixes #877 
- fixes #878 (I see work is done on oponeo domains, if it fixes oponeo.nl this one can be removed)
- fixes #880 
- fixes #881 
- fixes #882 
- fixes #883 
- fixes #884 
- fixes #887 
- fixes #889 
- fixes #890 
- fixes #892 
- fixes #894
- fixes #895
- fixes #896 
- fixes #899 
- fixes #901 
- fixes #902 
- fixes #903
- fixes #904
- fixes #905 
- fixes #907 
- fixes #908 
- fixes #909 
- fixes #910

### CODE REVIEW

**Comment by krystian3w** [comment]
on allegro.cz see fake margin: https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/issues/123#issuecomment-1235118109
https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/commit/eff49752e6726fb6d222044b7db0b25fed5d4b6d

**Comment by OhMyGuus** [comment]
Sorry for late look & not working on it this week myself, but I really but also really apricate the work u do 💯 😄

**Comment by krystian3w** [comment]
@appeasementPolitik bad works your ` .meqh_en{overflow:unset !important}` at #5615

**Comment by krystian3w** [comment]
Maybe these works in Stylus:

```css
@-moz-document domain("allegro.cz") {
 .meqh_en.meqh_en:not(#glitch) { overflow: auto !important }
}
```

and these in uBo or AdGuard:

```adb
allegro.cz#$##.meqh_en.meqh_en:not(#glitch) { overflow: auto !important }
}

**Pull request merged**
