### PR TITLE
fixing scroll filters

### PR DESCRIPTION
**Pull request by ghost**
every website should be fixed ; the others are either already fixed or fake issues

Added support for https://sunpixels.eprimo.de/
Added support for https://play.esea.net/
Added support for https://guus.ninja/
Added support for https://radio.hrt.hr/
Added support for https://www.humanic.net/
Added support for https://www.ihk.de/
Added support for https://klarta.pl/
Added support for https://kontist.com/
Added support for https://lapoesiefacile.com/
Added support for https://mainwp.com/
Added support for https://www.make-it-in-germany.com/
Added support for https://www.dt.mef.gov.it/
Added support for https://www.moerfelden-walldorf.de/
Added support for https://www.mv-online.de/
Added support for https://www.mybestbrands.de/
Added support for https://www.myunidays.com/
Added support for https://www.presseportal.de/
Added support for https://press.princeton.edu/
Added support for https://www.refurbed.de/
Added support for https://region-bayreuth.de/
Added support for https://www.resume.se/
Added support for https://support.industry.siemens.com/
Added support for https://www.soliver.si/
Added support for https://www.soudal.de/
Added support for https://soundcloud.com/
Added support for https://sportland.ee/
Added support for https://tarnkappe.info/
Added support for https://www.tech-faq.net/
Added support for https://www.tenforums.com/
Added support for https://www.thega-filmpalast.de/
Added support for https://ton.org/
Added support for https://www.trendmutti.com/
Added support for https://www.tvo.de/
Added support for https://www.med.uni-rostock.de/
Added support for https://pawsact.vier-pfoten.de/
Added support for https://www.vogelsbergkreis.de/
Added support for https://www.withings.com/

{auto_update}

### CODE REVIEW

**Comment by azgaresncf** [comment]
Sorry if it is quite a mess, I had to reorder ALL of the ids' objects in the JSON file (and to do it manually as well)
```python
import json

def corriger_ids_consecutifs(fichier_entree, fichier_sortie):
    with open(fichier_entree, 'r') as fichier_json:
        donnees = json.load(fichier_json)

    for index, objet in enumerate(donnees):
        objet['id'] = index + 1

        if 'resourceTypes' in objet['condition']:
            resource_types_str = json.dumps(objet['condition']['resourceTypes'], separators=(',', ':'))
            objet['condition']['resourceTypes'] = f'resourceTypes: {resource_types_str[:-1][1:]}],'

    with open(fichier_sortie, 'w') as fichier_json_sortie:
        json.dump(donnees, fichier_json_sortie, indent=2)

corriger_ids_consecutifs('votre_fichier.json', 'fichier_corrigé.json')
```

**Comment by OhMyGuus** [comment]
> Sorry if it is quite a mess, I had to reorder ALL of the ids' objects in the JSON file (and to do it manually as well)
> 
> ```python
> import json
> 
> def corriger_ids_consecutifs(fichier_entree, fichier_sortie):
>     with open(fichier_entree, 'r') as fichier_json:
>         donnees = json.load(fichier_json)
> 
>     for index, objet in enumerate(donnees):
>         objet['id'] = index + 1
> 
>         if 'resourceTypes' in objet['condition']:
>             resource_types_str = json.dumps(objet['condition']['resourceTypes'], separators=(',', ':'))
>             objet['condition']['resourceTypes'] = f'resourceTypes: {resource_types_str[:-1][1:]}],'
> 
>     with open(fichier_sortie, 'w') as fichier_json_sortie:
>         json.dump(donnees, fichier_json_sortie, indent=2)
> 
> corriger_ids_consecutifs('votre_fichier.json', 'fichier_corrigé.json')
> ```

Oh the ignore the rules.json next time that is a automatic file which is being updated automatically, so even if you make a change into it it will be overwritten by the action

**Comment by azgaresncf** [comment]
oh
I will close this PR

**Comment by azgaresncf** [comment]
> oh I will close this PR
I'm going to a better PR lmao

**Pull request closed without merging**
