### PR TITLE
[WIP] Updating Manifest V3

### LINKED ISSUE #4: Chromium complains about Manifest version 2 being deprecated
Hello,

I was able to install the zip file in Chromium on Linux as per instructions. Just open Settings, Extensions and drag and drop the zip file on it.
However, Chromium complains about Manifest version 2 being deprecated. 
Is there something that could be done about that?

Kind regards.

### PR DESCRIPTION
**Pull request by OhMyGuus**
Updating to manifest v3 because all new extension on Chrome  are required to be using ManifestV3. 

Fixes #4

### CODE REVIEW

**Comment by krystian3w** [comment]
For now Mozilla no require V3 and may no support install in Nightly.

**Comment by OhMyGuus** [comment]
Just to inform it is a bit more work than I was initially thinking, this is because chrome decided to deprecate webrequestblocking in favor of declarativeNetRequest. 

This means I need to rewrite the blocking feature to load all the blocked url's on load of the extension.

**Comment by OhMyGuus** [comment]
The blocklist is now converted, now is only whitelisting & testing left :)

**Comment by OhMyGuus** [comment]
It still needs a lot of rewriting (bcs it is now using 2 lists as rules) planning to do that after I merge this so I can at least get it to the store & everything is setup since that requires more testing.

**Comment by OhMyGuus** [comment]
PR is not 100% finished yet but will create a new one for the cleanup :)

**Comment by krystian3w** [comment]
https://blog.mozilla.org/addons/2022/11/17/manifest-v3-signing-available-november-21-on-firefox-nightly/

**Pull request merged**
